
namespace Problem2_EvenFibonacciNumbers {
    /* Problem:
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89 ...
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

    class Program {
        public static void Main(string[] args) {
            
            Console.WriteLine("{0:n0}", FindFibonacciSum(4_000_000));

        }

        static int FindFibonacciSum(int upperLimit) {
            int previousNum = 1;
            int currentNum = 2;
            int fibSum = 0;
            int totalSum = 0;
            while (currentNum < upperLimit) {
                if (currentNum % 2 == 0) {      // because we want only even-valued terms
                    totalSum += currentNum;
                }
                fibSum = previousNum + currentNum;
                previousNum = currentNum;
                currentNum = fibSum;
            }
            return totalSum;
        }
    }
}